global using FluentValidation.TestHelper;
global using Microsoft.EntityFrameworkCore;
global using MockQueryable.Moq;
global using Moq;
global using TradingJournal.Modules.TradingSetup.Common.Enum;
global using TradingJournal.Modules.TradingSetup.Domain;
global using TradingJournal.Modules.TradingSetup.Features.V1.TradingSetups;
global using TradingJournal.Modules.TradingSetup.Infrastructure;
global using TradingSetup = TradingJournal.Modules.TradingSetup.Domain.TradingSetup;
global using TradingJournal.Shared.Abstractions;
global using TradingJournal.Shared.Contracts;
global using TradingJournal.Shared.Interfaces;
global using Xunit;
