// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingJournal.Modules.AiInsights.Infrastructure;

#nullable disable

namespace TradingJournal.Modules.AiInsights.Migrations
{
    [DbContext(typeof(AiInsightsDbContext))]
    partial class AiInsightsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradingJournal.Modules.AiInsights.Domain.MorningBriefing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionItem")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Briefing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("BriefingDateUtc")
                        .HasColumnType("date");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FocusAreasJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Greeting")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("OverallMood")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy", "BriefingDateUtc")
                        .IsUnique();

                    b.ToTable("MorningBriefings", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.AiInsights.Domain.TradingReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiActionItems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AiCriticalMistakesPsychological")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AiCriticalMistakesTechnical")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AiPsychologyAnalysis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AiStrengths")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AiSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AiSummaryGenerating")
                        .HasColumnType("bit");

                    b.Property<string>("AiTechnicalInsights")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AiWeaknesses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AiWhatToImprove")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeriodType")
                        .HasColumnType("int");

                    b.Property<int>("RuleBreaks")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPnl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TradingReviews", "Trades", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
