// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingJournal.Modules.Scanner.Infrastructure;

#nullable disable

namespace TradingJournal.Modules.Scanner.Migrations
{
    [DbContext(typeof(ScannerDbContext))]
    partial class ScannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradingJournal.Modules.Scanner.Domain.ScannerAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfluenceScore")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DetectionTimeframe")
                        .HasColumnType("int");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDismissed")
                        .HasColumnType("bit");

                    b.Property<int>("PatternType")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtDetection")
                        .HasColumnType("decimal(28,10)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Timeframe")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ZoneHighPrice")
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal?>("ZoneLowPrice")
                        .HasColumnType("decimal(28,10)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DetectedAt")
                        .HasDatabaseName("IX_ScannerAlerts_UserDetectedAt");

                    b.HasIndex("UserId", "Symbol", "PatternType", "DetectionTimeframe", "DetectedAt")
                        .HasDatabaseName("IX_ScannerAlerts_Dedup");

                    b.ToTable("ScannerAlerts", "Scanner");
                });

            modelBuilder.Entity("TradingJournal.Modules.Scanner.Domain.ScannerConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("bit");

                    b.Property<int>("MinConfluenceScore")
                        .HasColumnType("int");

                    b.Property<int>("ScanIntervalSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_ScannerConfigs_UserId");

                    b.ToTable("ScannerConfigs", "Scanner");
                });

            modelBuilder.Entity("TradingJournal.Modules.Scanner.Domain.ScannerConfigPattern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<int>("PatternType")
                        .HasColumnType("int");

                    b.Property<int>("ScannerConfigId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ScannerConfigId", "PatternType")
                        .IsUnique()
                        .HasDatabaseName("IX_ScannerConfigPatterns_ConfigPattern");

                    b.ToTable("ScannerConfigPatterns", "Scanner");
                });

            modelBuilder.Entity("TradingJournal.Modules.Scanner.Domain.ScannerConfigTimeframe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<int>("ScannerConfigId")
                        .HasColumnType("int");

                    b.Property<int>("Timeframe")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ScannerConfigId", "Timeframe")
                        .IsUnique()
                        .HasDatabaseName("IX_ScannerConfigTimeframes_ConfigTimeframe");

                    b.ToTable("ScannerConfigTimeframes", "Scanner");
                });

            modelBuilder.Entity("TradingJournal.Modules.Scanner.Domain.Watchlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Watchlists", "Scanner");
                });

            modelBuilder.Entity("TradingJournal.Modules.Scanner.Domain.WatchlistAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WatchlistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WatchlistId", "Symbol")
                        .IsUnique()
                        .HasDatabaseName("IX_WatchlistAssets_WatchlistSymbol");

                    b.ToTable("WatchlistAssets", "Scanner");
                });

            modelBuilder.Entity("TradingJournal.Modules.Scanner.Domain.WatchlistAssetDetector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("PatternType")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WatchlistAssetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WatchlistAssetId", "PatternType")
                        .IsUnique()
                        .HasDatabaseName("IX_WatchlistAssetDetectors_AssetPattern");

                    b.ToTable("WatchlistAssetDetectors", "Scanner");
                });

            modelBuilder.Entity("TradingJournal.Modules.Scanner.Domain.ScannerConfigPattern", b =>
                {
                    b.HasOne("TradingJournal.Modules.Scanner.Domain.ScannerConfig", "ScannerConfig")
                        .WithMany("EnabledPatterns")
                        .HasForeignKey("ScannerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannerConfig");
                });

            modelBuilder.Entity("TradingJournal.Modules.Scanner.Domain.ScannerConfigTimeframe", b =>
                {
                    b.HasOne("TradingJournal.Modules.Scanner.Domain.ScannerConfig", "ScannerConfig")
                        .WithMany("EnabledTimeframes")
                        .HasForeignKey("ScannerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannerConfig");
                });

            modelBuilder.Entity("TradingJournal.Modules.Scanner.Domain.WatchlistAsset", b =>
                {
                    b.HasOne("TradingJournal.Modules.Scanner.Domain.Watchlist", "Watchlist")
                        .WithMany("Assets")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("TradingJournal.Modules.Scanner.Domain.WatchlistAssetDetector", b =>
                {
                    b.HasOne("TradingJournal.Modules.Scanner.Domain.WatchlistAsset", "WatchlistAsset")
                        .WithMany("EnabledDetectors")
                        .HasForeignKey("WatchlistAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WatchlistAsset");
                });

            modelBuilder.Entity("TradingJournal.Modules.Scanner.Domain.ScannerConfig", b =>
                {
                    b.Navigation("EnabledPatterns");

                    b.Navigation("EnabledTimeframes");
                });

            modelBuilder.Entity("TradingJournal.Modules.Scanner.Domain.Watchlist", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("TradingJournal.Modules.Scanner.Domain.WatchlistAsset", b =>
                {
                    b.Navigation("EnabledDetectors");
                });
#pragma warning restore 612, 618
        }
    }
}
