// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingJournal.Modules.Trades.Infrastructure;

#nullable disable

namespace TradingJournal.Modules.Trades.Migrations
{
    [DbContext(typeof(TradeDbContext))]
    [Migration("20260302030157_add description column to trading zone")]
    partial class adddescriptioncolumntotradingzone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.PretradeChecklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckListType")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PretradeChecklists", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.RiskGuardrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AccountEquity")
                        .HasColumnType("float");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<double?>("MaxDailyLoss")
                        .HasColumnType("float");

                    b.Property<double?>("PositionSize")
                        .HasColumnType("float");

                    b.Property<double?>("RiskPercentage")
                        .HasColumnType("float");

                    b.Property<double?>("TakeProfit")
                        .HasColumnType("float");

                    b.Property<int?>("TradeHistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TradeHistoryId");

                    b.ToTable("RiskGuardrails", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TechnicalAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TechnicalAnalyses", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeEmotionTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmotionTagId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<int>("TradeHistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TradeHistoryId");

                    b.ToTable("TradeEmotionTags", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ConfidenceLevel")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("EntryPrice")
                        .HasColumnType("float");

                    b.Property<double?>("ExitPrice")
                        .HasColumnType("float");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Pnl")
                        .HasColumnType("float");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("PsychologyNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RiskGuardrailId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("StopLoss")
                        .HasColumnType("float");

                    b.Property<double>("TargetTier1")
                        .HasColumnType("float");

                    b.Property<double?>("TargetTier2")
                        .HasColumnType("float");

                    b.Property<double?>("TargetTier3")
                        .HasColumnType("float");

                    b.Property<int?>("TradingSessionId")
                        .HasColumnType("int");

                    b.Property<int?>("TradingZoneId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RiskGuardrailId");

                    b.HasIndex("TradingSessionId");

                    b.ToTable("TradeHistories", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeHistoryChecklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<int>("PretradeChecklistId")
                        .HasColumnType("int");

                    b.Property<int>("TradeHistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PretradeChecklistId");

                    b.HasIndex("TradeHistoryId");

                    b.ToTable("TradeHistoryChecklists", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeScreenShot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<int>("TradeHistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TradeHistoryId");

                    b.ToTable("TradeScreenshots", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeTechnicalAnalysisTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<int>("TechnicalAnalysisId")
                        .HasColumnType("int");

                    b.Property<int>("TradeHistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TechnicalAnalysisId");

                    b.HasIndex("TradeHistoryId");

                    b.ToTable("TradeTechnicalAnalysisTags", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TradingSessions", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradingZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TradingZones", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.RiskGuardrail", b =>
                {
                    b.HasOne("TradingJournal.Modules.Trades.Domain.TradeHistory", "TradeHistory")
                        .WithMany()
                        .HasForeignKey("TradeHistoryId");

                    b.Navigation("TradeHistory");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeEmotionTag", b =>
                {
                    b.HasOne("TradingJournal.Modules.Trades.Domain.TradeHistory", "TradeHistory")
                        .WithMany("TradeEmotionTags")
                        .HasForeignKey("TradeHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeHistory");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeHistory", b =>
                {
                    b.HasOne("TradingJournal.Modules.Trades.Domain.RiskGuardrail", "RiskGuardrail")
                        .WithMany()
                        .HasForeignKey("RiskGuardrailId");

                    b.HasOne("TradingJournal.Modules.Trades.Domain.TradingSession", "TradingSession")
                        .WithMany()
                        .HasForeignKey("TradingSessionId");

                    b.Navigation("RiskGuardrail");

                    b.Navigation("TradingSession");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeHistoryChecklist", b =>
                {
                    b.HasOne("TradingJournal.Modules.Trades.Domain.PretradeChecklist", "PretradeChecklist")
                        .WithMany()
                        .HasForeignKey("PretradeChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingJournal.Modules.Trades.Domain.TradeHistory", "TradeHistory")
                        .WithMany("TradeChecklists")
                        .HasForeignKey("TradeHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PretradeChecklist");

                    b.Navigation("TradeHistory");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeScreenShot", b =>
                {
                    b.HasOne("TradingJournal.Modules.Trades.Domain.TradeHistory", "TradeHistory")
                        .WithMany("TradeScreenShots")
                        .HasForeignKey("TradeHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeHistory");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeTechnicalAnalysisTag", b =>
                {
                    b.HasOne("TradingJournal.Modules.Trades.Domain.TechnicalAnalysis", "TechnicalAnalysis")
                        .WithMany()
                        .HasForeignKey("TechnicalAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingJournal.Modules.Trades.Domain.TradeHistory", "TradeHistory")
                        .WithMany("TradeTechnicalAnalysisTags")
                        .HasForeignKey("TradeHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TechnicalAnalysis");

                    b.Navigation("TradeHistory");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeHistory", b =>
                {
                    b.Navigation("TradeChecklists");

                    b.Navigation("TradeEmotionTags");

                    b.Navigation("TradeScreenShots");

                    b.Navigation("TradeTechnicalAnalysisTags");
                });
#pragma warning restore 612, 618
        }
    }
}
