// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingJournal.Modules.Trades.Infrastructure;

#nullable disable

namespace TradingJournal.Modules.Trades.Migrations
{
    [DbContext(typeof(TradeDbContext))]
    [Migration("20260429060838_AddReviewWizard")]
    partial class AddReviewWizard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.ChecklistModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ChecklistModels", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.DisciplineLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisciplineRuleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TradeHistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("WasFollowed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineRuleId");

                    b.HasIndex("TradeHistoryId");

                    b.ToTable("DisciplineLogs", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.DisciplineRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DisciplineRules", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.LessonLearned", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionItems")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImpactScore")
                        .HasColumnType("int");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("KeyTakeaway")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LessonsLearned", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.LessonTradeLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<int>("LessonLearnedId")
                        .HasColumnType("int");

                    b.Property<int>("TradeHistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LessonLearnedId");

                    b.HasIndex("TradeHistoryId");

                    b.ToTable("LessonTradeLinks", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.PretradeChecklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckListType")
                        .HasColumnType("int");

                    b.Property<int>("ChecklistModelId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistModelId");

                    b.ToTable("PretradeChecklists", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.ReviewActionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TradingReviewId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TradingReviewId");

                    b.ToTable("ReviewActionItems", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TechnicalAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TechnicalAnalysis", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeEmotionTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmotionTagId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<int>("TradeHistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TradeHistoryId");

                    b.ToTable("TradeEmotionTags", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Asset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ConfidenceLevel")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EntryPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ExitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("HitStopLoss")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRuleBroken")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Pnl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("RuleBreakReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("StopLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TargetTier1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetTier2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TargetTier3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TradingResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TradingSessionId")
                        .HasColumnType("int");

                    b.Property<int?>("TradingSetupId")
                        .HasColumnType("int");

                    b.Property<int?>("TradingSummaryId")
                        .HasColumnType("int");

                    b.Property<int?>("TradingZoneId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TradingSessionId");

                    b.HasIndex("TradingZoneId");

                    b.ToTable("TradeHistories", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeHistoryChecklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<int>("PretradeChecklistId")
                        .HasColumnType("int");

                    b.Property<int>("TradeHistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PretradeChecklistId");

                    b.HasIndex("TradeHistoryId");

                    b.ToTable("TradeHistoryChecklists", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeScreenShot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<int>("TradeHistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TradeHistoryId");

                    b.ToTable("TradeScreenshots", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeTechnicalAnalysisTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<int>("TechnicalAnalysisId")
                        .HasColumnType("int");

                    b.Property<int>("TradeHistoryId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TechnicalAnalysisId");

                    b.HasIndex("TradeHistoryId");

                    b.ToTable("TradeTechnicalAnalysisTags", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradingProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisciplineEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxConsecutiveLosses")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxDailyLossPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaxTradesPerDay")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TradingProfiles", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradingReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BestTradeReflection")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisciplineNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("DisciplineRating")
                        .HasColumnType("int");

                    b.Property<int?>("ExecutionRating")
                        .HasColumnType("int");

                    b.Property<string>("GoalsForNextPeriod")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("KeyTakeaways")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<int?>("OverallRating")
                        .HasColumnType("int");

                    b.Property<string>("PerformanceNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeriodType")
                        .HasColumnType("int");

                    b.Property<string>("PsychologyNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("PsychologyRating")
                        .HasColumnType("int");

                    b.Property<int?>("RiskManagementRating")
                        .HasColumnType("int");

                    b.Property<int>("RuleBreaks")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPnl")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalTrades")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.Property<string>("WorstTradeReflection")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("TradingReviews", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FromTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PnL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ToTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TradeCount")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TradingSessions", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradingZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TradingZones", "Trades");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.DisciplineLog", b =>
                {
                    b.HasOne("TradingJournal.Modules.Trades.Domain.DisciplineRule", "DisciplineRule")
                        .WithMany("DisciplineLogs")
                        .HasForeignKey("DisciplineRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingJournal.Modules.Trades.Domain.TradeHistory", "TradeHistory")
                        .WithMany()
                        .HasForeignKey("TradeHistoryId");

                    b.Navigation("DisciplineRule");

                    b.Navigation("TradeHistory");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.LessonTradeLink", b =>
                {
                    b.HasOne("TradingJournal.Modules.Trades.Domain.LessonLearned", "LessonLearned")
                        .WithMany("LessonTradeLinks")
                        .HasForeignKey("LessonLearnedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingJournal.Modules.Trades.Domain.TradeHistory", "TradeHistory")
                        .WithMany()
                        .HasForeignKey("TradeHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonLearned");

                    b.Navigation("TradeHistory");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.PretradeChecklist", b =>
                {
                    b.HasOne("TradingJournal.Modules.Trades.Domain.ChecklistModel", "ChecklistModel")
                        .WithMany("Criteria")
                        .HasForeignKey("ChecklistModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistModel");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.ReviewActionItem", b =>
                {
                    b.HasOne("TradingJournal.Modules.Trades.Domain.TradingReview", "TradingReview")
                        .WithMany("ActionItems")
                        .HasForeignKey("TradingReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradingReview");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeEmotionTag", b =>
                {
                    b.HasOne("TradingJournal.Modules.Trades.Domain.TradeHistory", "TradeHistory")
                        .WithMany("TradeEmotionTags")
                        .HasForeignKey("TradeHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeHistory");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeHistory", b =>
                {
                    b.HasOne("TradingJournal.Modules.Trades.Domain.TradingSession", "TradingSession")
                        .WithMany()
                        .HasForeignKey("TradingSessionId");

                    b.HasOne("TradingJournal.Modules.Trades.Domain.TradingZone", "TradingZone")
                        .WithMany()
                        .HasForeignKey("TradingZoneId");

                    b.Navigation("TradingSession");

                    b.Navigation("TradingZone");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeHistoryChecklist", b =>
                {
                    b.HasOne("TradingJournal.Modules.Trades.Domain.PretradeChecklist", "PretradeChecklist")
                        .WithMany()
                        .HasForeignKey("PretradeChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingJournal.Modules.Trades.Domain.TradeHistory", "TradeHistory")
                        .WithMany("TradeChecklists")
                        .HasForeignKey("TradeHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PretradeChecklist");

                    b.Navigation("TradeHistory");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeScreenShot", b =>
                {
                    b.HasOne("TradingJournal.Modules.Trades.Domain.TradeHistory", "TradeHistory")
                        .WithMany("TradeScreenShots")
                        .HasForeignKey("TradeHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeHistory");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeTechnicalAnalysisTag", b =>
                {
                    b.HasOne("TradingJournal.Modules.Trades.Domain.TechnicalAnalysis", "TechnicalAnalysis")
                        .WithMany()
                        .HasForeignKey("TechnicalAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradingJournal.Modules.Trades.Domain.TradeHistory", "TradeHistory")
                        .WithMany("TradeTechnicalAnalysisTags")
                        .HasForeignKey("TradeHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TechnicalAnalysis");

                    b.Navigation("TradeHistory");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.ChecklistModel", b =>
                {
                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.DisciplineRule", b =>
                {
                    b.Navigation("DisciplineLogs");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.LessonLearned", b =>
                {
                    b.Navigation("LessonTradeLinks");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradeHistory", b =>
                {
                    b.Navigation("TradeChecklists");

                    b.Navigation("TradeEmotionTags");

                    b.Navigation("TradeScreenShots");

                    b.Navigation("TradeTechnicalAnalysisTags");
                });

            modelBuilder.Entity("TradingJournal.Modules.Trades.Domain.TradingReview", b =>
                {
                    b.Navigation("ActionItems");
                });
#pragma warning restore 612, 618
        }
    }
}
