// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingJournal.Modules.Setups.Infrastructure;

#nullable disable

namespace TradingJournal.Modules.Setups.Migrations
{
    [DbContext(typeof(SetupDbContext))]
    [Migration("20260504094455_AddSoftDeleteQueryFilters")]
    partial class AddSoftDeleteQueryFilters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradingJournal.Modules.Setups.Domain.SetupConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsAnimated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceStepId")
                        .HasColumnType("int");

                    b.Property<int>("TargetStepId")
                        .HasColumnType("int");

                    b.Property<int>("TradingSetupId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SourceStepId");

                    b.HasIndex("TargetStepId");

                    b.HasIndex("TradingSetupId");

                    b.ToTable("SetupConnections", "Setups");
                });

            modelBuilder.Entity("TradingJournal.Modules.Setups.Domain.SetupStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PositionX")
                        .HasColumnType("float");

                    b.Property<double>("PositionY")
                        .HasColumnType("float");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<int>("TradingSetupId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TradingSetupId");

                    b.ToTable("SetupSteps", "Setups");
                });

            modelBuilder.Entity("TradingJournal.Modules.Setups.Domain.TradingSetup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryRules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExitRules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdealMarketConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredAssets")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredTimeframes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("RetiredDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RetiredReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RiskPerTrade")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("TargetRiskReward")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("TradingSetups", "Setups");
                });

            modelBuilder.Entity("TradingJournal.Modules.Setups.Domain.SetupConnection", b =>
                {
                    b.HasOne("TradingJournal.Modules.Setups.Domain.SetupStep", "SourceStep")
                        .WithMany()
                        .HasForeignKey("SourceStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradingJournal.Modules.Setups.Domain.SetupStep", "TargetStep")
                        .WithMany()
                        .HasForeignKey("TargetStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradingJournal.Modules.Setups.Domain.TradingSetup", "TradingSetup")
                        .WithMany("Connections")
                        .HasForeignKey("TradingSetupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceStep");

                    b.Navigation("TargetStep");

                    b.Navigation("TradingSetup");
                });

            modelBuilder.Entity("TradingJournal.Modules.Setups.Domain.SetupStep", b =>
                {
                    b.HasOne("TradingJournal.Modules.Setups.Domain.TradingSetup", "TradingSetup")
                        .WithMany("Steps")
                        .HasForeignKey("TradingSetupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradingSetup");
                });

            modelBuilder.Entity("TradingJournal.Modules.Setups.Domain.TradingSetup", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
